In [1]:
import numpy as np

In [2]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [4]:
result = [(x if c else y)
             for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [6]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [7]:
arr = np.random.randn(5, 4)
arr

array([[ 1.19177015, -0.3409322 , -0.99522706, -1.86512495],
       [-0.64119864, -1.24291636, -1.54500294,  0.13751537],
       [ 0.94061521, -1.14253937,  0.29622991, -0.30016449],
       [ 0.86049386,  0.88021139,  0.75214107, -0.66842098],
       [ 0.28117737,  0.76153243, -0.26629856, -1.54977585]])

In [10]:
arr.mean()

-0.22279573269026787

In [11]:
arr.sum()

-4.455914653805357

In [12]:
(arr > 0).sum()

9

In [14]:
bools = np.array([False, False, True, False])
print('{} --  {}'.format(bools.any(), bools.all()))

True --  False


In [15]:
arr.sort()
arr

array([[-1.86512495, -0.99522706, -0.3409322 ,  1.19177015],
       [-1.54500294, -1.24291636, -0.64119864,  0.13751537],
       [-1.14253937, -0.30016449,  0.29622991,  0.94061521],
       [-0.66842098,  0.75214107,  0.86049386,  0.88021139],
       [-1.54977585, -0.26629856,  0.28117737,  0.76153243]])

In [16]:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))]

-1.6412410243529345

In [20]:
np.save('some_array', arr)
np.savez('array_archive.npz', a=arr, b=arr)
np.savez_compressed('arrays_compressed.npz', a=arr, b=arr)

In [18]:
np.load('some_array.npy')

array([[-1.86512495, -0.99522706, -0.3409322 ,  1.19177015],
       [-1.54500294, -1.24291636, -0.64119864,  0.13751537],
       [-1.14253937, -0.30016449,  0.29622991,  0.94061521],
       [-0.66842098,  0.75214107,  0.86049386,  0.88021139],
       [-1.54977585, -0.26629856,  0.28117737,  0.76153243]])