In [3]:
import numpy as np
from numpy.linalg import inv, qr

In [6]:
X = np.random.randn(5, 5)
mat = X.T.dot(X)
inv(mat)

array([[  6589.18757785,  -1714.45725314, -17024.42957386,
          9177.85968008, -13711.96436676],
       [ -1714.45725314,    446.45943764,   4430.41667156,
         -2388.33102436,   3568.19968466],
       [-17024.42957386,   4430.41667156,  43990.49528493,
        -23714.88974293,  35430.50562524],
       [  9177.85968008,  -2388.33102436, -23714.88974293,
         12784.64316269, -19100.33414497],
       [-13711.96436676,   3568.19968466,  35430.50562524,
        -19100.33414497,  28536.64958133]])

In [7]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -3.25787136e-13, -9.36947095e-13,
        -8.67657142e-12,  4.78644580e-12],
       [ 3.57353173e-12,  1.00000000e+00, -3.75081150e-12,
        -7.93970487e-13, -4.04750019e-12],
       [ 6.64633495e-12, -3.86983128e-12,  1.00000000e+00,
         2.37699081e-11, -1.36108507e-11],
       [-9.30971026e-14,  1.44204952e-12,  2.05266818e-11,
         1.00000000e+00,  2.06217412e-11],
       [-1.06658337e-11,  2.97034773e-12, -3.06023269e-12,
        -1.63460721e-11,  1.00000000e+00]])

In [8]:
q, r = qr(mat)
r

array([[-2.94052648e+00, -1.11288005e+00,  4.31444474e+00,
         6.39446615e+00, -2.35053115e+00],
       [ 0.00000000e+00, -5.36906634e+00,  4.00940201e+00,
         4.14314611e+00, -1.53353139e+00],
       [ 0.00000000e+00,  0.00000000e+00, -2.88667851e+00,
        -4.60803461e+00,  4.99763495e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -3.84723312e+00, -2.57508091e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.94800657e-05]])